### ISSUE TITLE
Attempted to trust a non-string value in a content requiring a string: Context: html

### ISSUE THREAD

**Issue by vaibhav-jain** [jirikavi/AngularJS-Toaster#259]
I'm getting this error when calling `toastr.pop`. Any idea what can be wrong ??

```
Error: [$sce:itype] Attempted to trust a non-string value in a content requiring a string: Context: html
http://errors.angularjs.org/1.4.3/$sce/itype?p0=html
    at http://192.168.0.102:8100/lib/ionic/js/ionic.bundle.js:8900:12
    at trustAs (http://192.168.0.102:8100/lib/ionic/js/ionic.bundle.js:25455:15)
    at Object.sce.(anonymous function) [as trustAsHtml] (http://192.168.0.102:8100/lib/ionic/js/ionic.bundle.js:26206:16)
    at u (https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.181/toaster.min.js:13:3767)
    at Array.e._onNewToast (https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.181/toaster.min.js:13:5477)
    at https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.181/toaster.min.js:13:1614
    at Scope.$emit (http://192.168.0.102:8100/lib/ionic/js/ionic.bundle.js:24924:33)
    at Object.pop (https://cdnjs.cloudflare.com/ajax/libs/angularjs-toaster/0.4.181/toaster.min.js:13:1279)
    at http://192.168.0.102:8100/js/app/todo/todo.js:75:19
    at processQueue (http://192.168.0.102:8100/lib/ionic/js/ionic.bundle.js:23399:28)
```

@jirikavi  Awesome plugin

**Comment by Stabzs** [comment]
This has nothing to do with the library.  You're passing a non string argument in a context where it absolutely expects a string.  Please create a complete plunker that demonstrates the issue and I'll be happy to point you in the right direction if possible.

**Comment by vaibhav-jain** [comment]
@Stabzs Sure I'll create and share plunkr
